# BMAD Configuration
version: "1.0"
project:
  name: "BMAD Architecture Agent"
  description: "Cloud architecture design and analysis agent"

defaults:
  cloud_providers: ["aws", "azure", "gcp"]
  compliance_frameworks: ["gdpr", "hipaa", "pci-dss", "sox", "iso-27001"]
  
agents:
  architect:
    description: "Cloud Architecture Expert"
    capabilities: ["design", "analyze", "review", "optimize"]

templates:
  enabled: true
  default_format: "markdown"

tools:
  cost_calculator: true
  diagram_generator: true
  compliance_checker: true
  service_selector: true