# BMAD Core Configuration for Cloud Architecture Project
# Powered by BMAD™ Core

markdownExploder: true

# Expansion Packs
expansionPacks:
  - cloud-architecture        # Cloud infrastructure design
  - data-architecture         # Database and data pipeline design
  - integration-patterns      # API and system integration
  - platform-engineering      # CI/CD, Kubernetes, IaC
  - architecture-governance   # ADRs, standards, reviews

# Quality Assurance
qa:
  qaLocation: docs/qa

# Requirements Documents
requirements:
  requirementsFile: docs/requirements.md
  requirementsVersion: v1
  requirementsLocation: docs/requirements

# Architecture Documents
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v1
  architectureSharded: true
  architectureShardedLocation: docs/architecture

# Cost Analysis
costAnalysis:
  costAnalysisFile: docs/cost-analysis.md
  costAnalysisLocation: docs/cost-analysis

# Security Assessment
security:
  securityAssessmentFile: docs/security-assessment.md
  securityLocation: docs/security

# Data Architecture
dataArchitecture:
  dataArchitectureFile: docs/data-architecture.md
  dataArchitectureLocation: docs/data-architecture
  erdLocation: docs/data-architecture/erd
  pipelineLocation: docs/data-architecture/pipelines

# Integration Architecture
integration:
  integrationFile: docs/integration.md
  integrationLocation: docs/integration
  apiSpecsLocation: docs/integration/api-specs
  eventSchemasLocation: docs/integration/event-schemas

# Platform Engineering
platform:
  platformFile: docs/platform.md
  platformLocation: docs/platform
  pipelinesLocation: docs/platform/pipelines
  kubernetesLocation: docs/platform/kubernetes
  iacLocation: docs/platform/iac

# Architecture Governance
governance:
  governanceFile: docs/governance.md
  adrsLocation: docs/architecture/decisions
  techRadarFile: docs/architecture/tech-radar.md
  standardsLocation: docs/architecture/standards
  reviewsLocation: docs/architecture/reviews

# Custom Technical Documents
customTechnicalDocuments:
  - docs/architecture/tech-stack.md
  - docs/architecture/deployment-plan.md
  - docs/architecture/monitoring-strategy.md

# Development Story Location (if using with BMAD core workflow)
devStoryLocation: docs/stories

# Slash Command Prefix
slashPrefix: ArchSuite

# Project Metadata
project:
  name: BMAD Architecture Suite
  description: Complete expert architect toolkit with cloud, data, integration, platform, and governance
  version: 2.0.0
